name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix-output: ${{ steps.set-matrix.outputs.matrix-output }}

    steps:
    - name: Set matrix
      id: set-matrix
      run: |
        echo "matrix-output={\"contexts\": [\"vusal\",\"alakbarov\",\"eldar\"]}" >> $GITHUB_OUTPUT

  use-matrix:
    needs: define-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mymatrix: ${{ fromJSON(needs.define-matrix.outputs.matrix-output) }}

    steps:
    - name: Use matrix ${{ matrix.mymatrix }}
      run: |
        echo "Using matrix: ${{ matrix.mymatrix }}"
