name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix-output: ${{ steps.set-matrix.outputs.matrix-output }}

    steps:
    - name: Set matrix
      id: set-matrix
      run: echo "::set-output name=matrix-output::one,two,three"

  use-matrix:
    needs: define-matrix
    runs-on: ubuntu-latest

    env:
      MY_MATRIX: ${{ needs.define-matrix.outputs.matrix-output }}

    strategy:
      matrix:
        mymatrix: [ "${{ env.MY_MATRIX }}" ]

    steps:
    - name: Use matrix
      run: |
        echo "Using matrix: ${{ matrix.mymatrix }}"
